[toolchain]
moc = "1.3.0"

[package]
name = "spotify-client"
version = "0.1.0"
description = "Generated Motoko client for Spotify Web API"
repository = "https://github.com/ggreif/openapi-generator/tree/master/samples/client/spotify/motoko/generated"
license = "Apache-2.0"
files = ["Apis/**/*.mo", "Models/**/*.mo"]

[dependencies]
core = "2.3.1"
serde-core = "0.0.1"
"cbor@4.1.0" = "4.1.0"
"itertools@0.2.2" = "0.2.2" # because for serde-core
xtended-numbers = "2.3.0"
"xtended-numbers@2.3.0" = "2.3.0" # because for ByteUtils (inlined in serde-core)
base = "0.14.13" # because serde-core uses json.mo submodule
"sha2@0.1.6" = "0.1.6"
