generatorName: motoko
outputDir: samples/client/yamaha-musiccast/motoko-test/generated
inputSpec: yamaha-musiccast-api.yaml
artifactId: yamaha-musiccast-client
artifactVersion: 1.0.0
additionalProperties:
  hideGenerationTimestamp: "true"
  useIcp: true
  projectName: yamaha_test
