generatorName: motoko
outputDir: samples/client/twilio/motoko/generated
inputSpec: samples/client/twilio/motoko/specs/twilio_api_v2010.json
artifactId: twilio-client
artifactVersion: 0.1.0
additionalProperties:
  hideGenerationTimestamp: "true"
  useDfx: false
  artifactRepoUrl: "https://github.com/caffeinelabs/twilio-client"
