[toolchain]
moc = "1.4.1"

[package]
name = "yamaha-test"
version = "1.0.0"
description = "Test project for Yamaha MusicCast API client"

[dependencies]
core = "2.4.0"
serde-core = "0.0.2"
"cbor@4.1.0" = "4.1.0"
"itertools@0.2.2" = "0.2.2" # because for serde-core
base = "0.14.13" # because serde-core uses json.mo submodule
xtended-numbers = "2.3.0"
"sha2@0.1.6" = "0.1.6"
